---
title: "Benchmark: Comparing the Monte Carlo Method with Nonparametric Bootstrapping"
author: "Ivan Jacob Agaloos Pesigan"
date: "2022-10-09"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Benchmark: Comparing the Monte Carlo Method with Nonparametric Bootstrapping}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---









We compare the Monte Carlo (MC) method with nonparametric bootstrapping (NB) using the simple mediation model with missing data.
One advantage of MC over NB is speed.
This is because the model is only fitted once in MC whereas it is fitted many times in NB.


```r
library(semmcci)
library(lavaan)
library(microbenchmark)
```

## Data


```r
n <- 1000
a <- 0.50
b <- 0.50
cp <- 0.25
s2_eM <- 1 - a^2
s2_eY <- 1 - cp^2 - a^2 * b^2 - b^2 * s2_eM - 2 * cp * a * b
eM <- rnorm(n = n, mean = 0, sd = sqrt(s2_eM))
eY <- rnorm(n = n, mean = 0, sd = sqrt(s2_eY))
X <- rnorm(n = n)
M <- a * X + eM
Y <- cp * X + b * M + eY
df <- data.frame(X, M, Y)

# Create data set with missing values.

miss <- sample(1:dim(df)[1], 300)
df[miss[1:100], "X"] <- NA
df[miss[101:200], "M"] <- NA
df[miss[201:300], "Y"] <- NA
```

## Model Specification

The indirect effect is defined by the product of the slopes
of paths `X` to `M` labeled as `a` and `M` to `Y` labeled as `b`.
In this example, we are interested in the confidence intervals of `indirect`
defined as the product of `a` and `b` using the `:=` operator
in the `lavaan` model syntax.


```r
model <- "
  Y ~ cp * X + b * M
  M ~ a * X
  indirect := a * b
  direct := cp
  total := cp + (a * b)
"
```

## Model Fitting

We can now fit the model using the `sem()` function from `lavaan`.
We are using `missing = "fiml"` to handle missing data in `lavaan`.
Since there are missing values in `x`, we also set `fixed.x = FALSE`.


```r
fit <- sem(data = df, model = model, missing = "fiml", fixed.x = FALSE)
```

## Monte Carlo Confidence Intervals

The `fit` `lavaan` object can then be passed to the `MC()` function from `semmcci`
to generate Monte Carlo confidence intervals.


```r
MC(fit, R = 500, alpha = c(0.001, 0.01, 0.05))
#> Monte Carlo Confidence Intervals
#>              est     se   R   0.05%    0.5%    2.5%  97.5%  99.5% 99.95%
#> cp        0.2335 0.0300 500  0.1564  0.1622  0.1763 0.2902 0.3092 0.3226
#> b         0.5112 0.0299 500  0.4221  0.4372  0.4521 0.5702 0.5866 0.5883
#> a         0.4809 0.0287 500  0.4064  0.4086  0.4257 0.5390 0.5538 0.5651
#> Y~~Y      0.5542 0.0272 500  0.4683  0.4857  0.5016 0.6060 0.6219 0.6251
#> M~~M      0.7564 0.0365 500  0.6580  0.6674  0.6896 0.8307 0.8470 0.8711
#> X~~X      1.0591 0.0508 500  0.9423  0.9502  0.9586 1.1564 1.1771 1.2089
#> Y~1      -0.0127 0.0253 500 -0.0895 -0.0770 -0.0621 0.0356 0.0462 0.0631
#> M~1      -0.0223 0.0270 500 -0.1274 -0.0862 -0.0728 0.0318 0.0422 0.0672
#> X~1       0.0025 0.0347 500 -0.0983 -0.0853 -0.0689 0.0750 0.0931 0.1062
#> indirect  0.2458 0.0205 500  0.1817  0.1938  0.2051 0.2834 0.2991 0.3055
#> direct    0.2335 0.0300 500  0.1564  0.1622  0.1763 0.2902 0.3092 0.3226
#> total     0.4794 0.0302 500  0.3954  0.4025  0.4182 0.5338 0.5531 0.5872
```

## Nonparametric Bootstrap Confidence Intervals

Nonparametric bootstrap confidence intervals can be generated in `lavaan` using the following.


```r
parameterEstimates(
  sem(
    data = df,
    model = model,
    missing = "fiml",
    fixed.x = FALSE,
    se = "bootstrap",
    bootstrap = 500
  )
)
#>         lhs op      rhs    label    est    se      z pvalue ci.lower ci.upper
#> 1         Y  ~        X       cp  0.234 0.028  8.297  0.000    0.181    0.288
#> 2         Y  ~        M        b  0.511 0.030 16.782  0.000    0.450    0.571
#> 3         M  ~        X        a  0.481 0.030 16.250  0.000    0.424    0.537
#> 4         Y ~~        Y           0.554 0.028 19.715  0.000    0.493    0.607
#> 5         M ~~        M           0.756 0.037 20.582  0.000    0.688    0.827
#> 6         X ~~        X           1.059 0.049 21.397  0.000    0.958    1.160
#> 7         Y ~1                   -0.013 0.026 -0.493  0.622   -0.061    0.037
#> 8         M ~1                   -0.022 0.029 -0.765  0.444   -0.080    0.035
#> 9         X ~1                    0.002 0.034  0.073  0.942   -0.063    0.070
#> 10 indirect :=      a*b indirect  0.246 0.020 12.050  0.000    0.207    0.286
#> 11   direct :=       cp   direct  0.234 0.028  8.289  0.000    0.181    0.288
#> 12    total := cp+(a*b)    total  0.479 0.027 17.493  0.000    0.428    0.533
```

## Benchmark

### Arguments




|Variables |Values |Notes                               |
|:---------|:------|:-----------------------------------|
|R         |5000   |Number of Monte Carlo replications. |
|B         |5000   |Number of bootstrap samples.        |




```r
benchmark01 <- microbenchmark(
  MC = {
    fit <- sem(
      data = df,
      model = model,
      missing = "fiml",
      fixed.x = FALSE
    )
    MC(
      fit,
      R = R,
      pd = FALSE
    )
  },
  NB = sem(
    data = df,
    model = model,
    missing = "fiml",
    fixed.x = FALSE,
    se = "bootstrap",
    bootstrap = B
  ),
  times = 10
)
```

### Summary of Benchmark Results


```r
summary(benchmark01, unit = "ms")
#>   expr         min          lq        mean     median          uq         max
#> 1   MC    202.1584    221.3008    269.0019    232.211    252.6618    607.0082
#> 2   NB 120385.4318 121013.3895 125186.0946 125857.477 128113.0535 129753.2585
#>   neval
#> 1    10
#> 2    10
```

### Summary of Benchmark Results Relative to the Faster Method


```r
summary(benchmark01, unit = "relative")
#>   expr      min       lq     mean   median       uq      max neval
#> 1   MC   1.0000   1.0000   1.0000   1.0000   1.0000   1.0000    10
#> 2   NB 595.5006 546.8275 465.3726 541.9963 507.0534 213.7587    10
```

## Benchmark - Monte Carlo Method with Precalculated Estimates




```r
fit <- sem(
  data = df,
  model = model,
  missing = "fiml",
  fixed.x = FALSE
)
benchmark02 <- microbenchmark(
  MC = MC(
    fit,
    R = R, 
    pd = FALSE
  ),
  NB = sem(
    data = df,
    model = model,
    missing = "fiml",
    fixed.x = FALSE,
    se = "bootstrap",
    bootstrap = B
  ),
  times = 10
)
```

### Summary of Benchmark Results


```r
summary(benchmark02, unit = "ms")
#>   expr         min          lq        mean      median          uq        max
#> 1   MC    126.4147    128.3207    133.4782    130.2673    137.3684    157.549
#> 2   NB 117632.8445 121631.1537 126764.5958 124766.4845 130567.9636 139686.071
#>   neval
#> 1    10
#> 2    10
```

### Summary of Benchmark Results Relative to the Faster Method


```r
summary(benchmark02, unit = "relative")
#>   expr      min       lq     mean   median      uq    max neval
#> 1   MC   1.0000   1.0000   1.0000   1.0000   1.000   1.00    10
#> 2   NB 930.5315 947.8686 949.7024 957.7731 950.495 886.62    10
```
