---
title: "Example 4.2: The Simple Mediation Model with Missing Data (MI)"
author: "Ivan Jacob Agaloos Pesigan"
date: "2025-07-22"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Cheung-2023
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Example 4.2: The Simple Mediation Model with Missing Data (MI)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- vignettes/example-4-2-simple-miss-mi.Rmd is generated from .setup/vignettes/example-4-2-simple-miss-mi.Rmd.orig. Please edit that file -->





In this example,
the Monte Carlo method is used to generate confidence intervals
for the indirect effect in a simple mediation model with missing data
where
variable `X` has an effect on variable `Y`,
through a mediating variable `M`
with multiply imputed data sets.


``` r
library(semmcci)
library(lavaan)
```

## Data




``` r
summary(df)
#>        X                   M                  Y           
#>  Min.   :-3.199558   Min.   :-3.37128   Min.   :-3.61432  
#>  1st Qu.:-0.632676   1st Qu.:-0.70516   1st Qu.:-0.66921  
#>  Median : 0.028235   Median : 0.02825   Median :-0.04834  
#>  Mean   : 0.002689   Mean   :-0.01992   Mean   :-0.01538  
#>  3rd Qu.: 0.657543   3rd Qu.: 0.65239   3rd Qu.: 0.65293  
#>  Max.   : 3.470910   Max.   : 2.93497   Max.   : 3.09950  
#>  NA's   :100         NA's   :100        NA's   :100
```

## Multiple Imputation

Perform the appropriate multiple imputation approach to deal with missing values.
In this example, we impute multivariate missing data under the normal model.


``` r
mi <- mice::mice(
  df,
  method = "norm",
  m = 100,
  print = FALSE,
  seed = 42
)
```

## Model Specification

The indirect effect is defined by the product of the slopes
of paths `X` to `M` labeled as `a` and `M` to `Y` labeled as `b`.
In this example, we are interested in the confidence intervals of `indirect`
defined as the product of `a` and `b` using the `:=` operator
in the `lavaan` model syntax.


``` r
model <- "
  Y ~ cp * X + b * M
  M ~ a * X
  X ~~ X
  indirect := a * b
  direct := cp
  total := cp + (a * b)
"
```

## Model Fitting

We can now fit the model using the `sem()` function from `lavaan`.
We do not need to deal with missing values in this stage.


``` r
fit <- sem(data = df, model = model)
```

## Monte Carlo Confidence Intervals

The `fit` `lavaan` object and `mi` `mids` object can then be passed to the `MCMI()` function from `semmcci`
to generate Monte Carlo confidence intervals
using multiple imputation
as described in Pesigan and Cheung (2023).


``` r
MCMI(fit, mi = mi, R = 20000L, alpha = 0.05, seed = 42)
#> Monte Carlo Confidence Intervals (Multiple Imputation Estimates)
#>             est     se     R   2.5%  97.5%
#> cp       0.2328 0.0300 20000 0.1748 0.2911
#> b        0.5113 0.0300 20000 0.4526 0.5702
#> a        0.4811 0.0287 20000 0.4245 0.5376
#> X~~X     1.0617 0.0495 20000 0.9649 1.1591
#> Y~~Y     0.5533 0.0272 20000 0.5001 0.6070
#> M~~M     0.7568 0.0361 20000 0.6856 0.8277
#> indirect 0.2460 0.0204 20000 0.2072 0.2868
#> direct   0.2328 0.0300 20000 0.1748 0.2911
#> total    0.4788 0.0286 20000 0.4215 0.5350
```

## Standardized Monte Carlo Confidence Intervals

Standardized Monte Carlo Confidence intervals can be generated by passing the result of the `MCMI()` function to the `MCStd()` function.


``` r
fit <- sem(data = df, model = model)
unstd <- MCMI(fit, mi = mi, R = 20000L, alpha = 0.05, seed = 42)
```


``` r
MCStd(unstd, alpha = 0.05)
#> Standardized Monte Carlo Confidence Intervals
#>             est     se     R   2.5%  97.5%
#> cp       0.2450 0.0307 20000 0.1810 0.3002
#> b        0.5189 0.0277 20000 0.4581 0.5666
#> a        0.5031 0.0260 20000 0.4428 0.5455
#> X~~X     1.0000 0.0000 20000 1.0000 1.0000
#> Y~~Y     0.5429 0.0252 20000 0.5074 0.6054
#> M~~M     0.7469 0.0258 20000 0.7024 0.8039
#> indirect 0.2610 0.0191 20000 0.2171 0.2916
#> direct   0.2450 0.0307 20000 0.1810 0.3002
#> total    0.5060 0.0263 20000 0.4411 0.5452
```

## References
