---
title: "Example 4.1: The Simple Mediation Model with Missing Data (FIML)"
author: "Ivan Jacob Agaloos Pesigan"
date: "2023-07-21"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Example 4.1: The Simple Mediation Model with Missing Data (FIML)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- vignettes/example-4-1-simple-miss-fiml.Rmd is generated from .setup/vignettes/example-4-1-simple-miss-fiml.Rmd.orig. Please edit that file -->



To cite `semmcci` in publications, please use: 

Pesigan, I. J. A., & Cheung, S. F. (2023).
Monte Carlo confidence intervals for the indirect effect with missing data.
*Behavior Research Methods*.
https://doi.org/10.3758/s13428-023-02114-4



In this example,
the Monte Carlo method is used to generate confidence intervals
for the indirect effect in a simple mediation model with missing data
where
variable `X` has an effect on variable `Y`,
through a mediating variable `M`.


```r
library(semmcci)
library(lavaan)
```

## Data




```r
summary(df)
#>        X                  M                  Y           
#>  Min.   :-3.19956   Min.   :-3.37128   Min.   :-3.61432  
#>  1st Qu.:-0.63268   1st Qu.:-0.70516   1st Qu.:-0.66921  
#>  Median : 0.02823   Median : 0.02825   Median :-0.04833  
#>  Mean   : 0.00269   Mean   :-0.01992   Mean   :-0.01538  
#>  3rd Qu.: 0.65754   3rd Qu.: 0.65240   3rd Qu.: 0.65293  
#>  Max.   : 3.47091   Max.   : 2.93497   Max.   : 3.09950  
#>  NA's   :100        NA's   :100        NA's   :100
```

## Model Specification

The indirect effect is defined by the product of the slopes
of paths `X` to `M` labeled as `a` and `M` to `Y` labeled as `b`.
In this example, we are interested in the confidence intervals of `indirect`
defined as the product of `a` and `b` using the `:=` operator
in the `lavaan` model syntax.


```r
model <- "
  Y ~ cp * X + b * M
  M ~ a * X
  X ~~ X
  indirect := a * b
  direct := cp
  total := cp + (a * b)
"
```

## Model Fitting

We can now fit the model using the `sem()` function from `lavaan`.
We are using `missing = "fiml"` to handle missing data in `lavaan`.


```r
fit <- sem(data = df, model = model, missing = "fiml")
```

## Monte Carlo Confidence Intervals

The `fit` `lavaan` object can then be passed to the `MC()` function from `semmcci`
to generate Monte Carlo confidence intervals.


```r
MC(fit, R = 20000L, alpha = 0.05)
#> Monte Carlo Confidence Intervals
#>              est     se     R    2.5%  97.5%
#> cp        0.2335 0.0293 20000  0.1763 0.2905
#> b         0.5113 0.0297 20000  0.4532 0.5691
#> a         0.4809 0.0288 20000  0.4242 0.5370
#> X~~X      1.0591 0.0492 20000  0.9634 1.1554
#> Y~~Y      0.5542 0.0268 20000  0.5018 0.6077
#> M~~M      0.7564 0.0361 20000  0.6857 0.8275
#> Y~1      -0.0127 0.0255 20000 -0.0623 0.0369
#> M~1      -0.0223 0.0291 20000 -0.0792 0.0344
#> X~1       0.0025 0.0336 20000 -0.0631 0.0683
#> indirect  0.2458 0.0203 20000  0.2074 0.2866
#> direct    0.2335 0.0293 20000  0.1763 0.2905
#> total     0.4794 0.0286 20000  0.4234 0.5356
```

## Standardized Monte Carlo Confidence Intervals

Standardized Monte Carlo Confidence intervals can be generated by passing the result of the `MC()` function to the `MCStd()` function.


```r
fit <- sem(data = df, model = model, missing = "fiml")
unstd <- MC(fit, R = 20000L, alpha = 0.05)
```


```r
MCStd(unstd, alpha = 0.05)
#> Standardized Monte Carlo Confidence Intervals
#>              est     se     R   2.5%  97.5%
#> cp        0.2409 0.0298 20000 0.1826 0.2989
#> b         0.5128 0.0269 20000 0.4589 0.5641
#> a         0.4946 0.0255 20000 0.4434 0.5438
#> X~~X      1.0000 0.0000 20000 1.0000 1.0000
#> Y~~Y      0.5568 0.0251 20000 0.5070 0.6054
#> M~~M      0.7554 0.0252 20000 0.7043 0.8034
#> indirect -0.0128 0.0188 20000 0.2169 0.2909
#> direct   -0.0222 0.0298 20000 0.1826 0.2989
#> total     0.0024 0.0257 20000 0.4433 0.5430
```
