[ -f /etc/bashrc ] && . /etc/bashrc
[ -f ~/.bash-neofetch ] && . ~/.bash-neofetch
[ -f ~/.bash-aliases ] && . ~/.bash-aliases
[ -f ~/.bash-path ] && . ~/.bash-path
[ -f ~/.bash-prompt ] && . ~/.bash-prompt
[ -f ~/.bash-secrets ] && . ~/.bash-secrets
[ -f ~/.bash-settings ] && . ~/.bash-settings
[ -f ~/.bash-variables ] && . ~/.bash-variables
[ -f ~/.bash-misc ] && . ~/.bash-misc
