# hadolint ignore=DL3007
FROM ijapesigan/r2u-r-project:latest

#ADD scripts /usr/src/local/src
#RUN chmod 777 /usr/src/local/src/setup.sh && \
#    ./usr/src/local/src/setup.sh          && \
#    rm -rf /usr/src/local/src
