name: Quarto Website (Quarto Pub)

on:
  workflow_run:
    workflows: [ "Make Project" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ijapesigan/docs
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: quarto-quarto-pub-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
    permissions:
      contents: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Build Project
        run: make build
      -
        name: Build Quarto Project
        run: make quarto
      - 
        name: _quarto.yml
        run: |
          FILE=.setup/quarto/_quarto.yml
          if [ -f "$FILE" ]; then
            cp "$FILE" .
          fi
      - 
        name: _publish.yml
        run: |
          FILE=.setup/quarto/_publish.yml
          if [ -f "$FILE" ]; then
            cp "$FILE" .
          fi
      -
        name: Deploy to Quarto Pub
        run: quarto publish --no-render quarto-pub
